Use error types coming from JSON-schema
OneKey-Network/OneKey-implementation pull request #273
Opened 2022-09-20 15:55 UTC by OlivierChirouze

2022-09-22 15:22 UTC, MohamedAmineGhazouani commented
Consider updating the addressability framework sub-module to get the latest changes on error.json.
You can run `git submodule update --recursive --remote` to get latest updates.

2022-09-22 15:28 UTC, MohamedAmineGhazouani requested changes
Consider updating the addressability framework sub-module to get the latest changes on error.json.
You can run `git submodule update --recursive --remote` to get latest updates.

2022-09-22 15:35 UTC, OlivierChirouze commented
Excellent point, thanks.
I thought Romain had updated the "generate model" script when he introduced git modules.
I will do it at the same time to avoid inconsistency.

2022-09-23 08:57 UTC, MohamedAmineGhazouani approved these changes

2022-09-23 09:07 UTC, merged